# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPad Air 13-inch (M2)",
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme("UITests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

erase_simulator(true)

launch_arguments(["--Reset"])

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

skip_open_summary(true)
reinstall_app(true)
stop_after_first_error(true)
number_of_retries(0)
concurrent_simulators(true)
output_simulator_logs(true)
headless(true)
erase_simulator(true)
